### ISSUE TITLE
Feature Request: Ability to import PresentMon logs

### ISSUE THREAD

**Issue by addisokw** [DevTechProfile/CapFrameX#1]
Would it be possible to get support for straight PresentMon csv files recorded outside of CapFrameX? Currently, they don't seem to be detected if you put them in the "observed" Captures directory.

The analysis tools look great, but i'd rather not have to install the full project on a given PC just to capture frame data.

**Comment by DevTechProfile** [comment]
Yes, of course. I will support that in the next version.

**Comment by Taxxor90** [comment]
> The analysis tools look great, but i'd rather not have to install the full project on a given PC just to capture frame data.
Out of curiosity:
I've never used PresentMon standalone but isn't it easier to have everything on one tool? I imagine even putting aside the analysis tools, the process of capturing frame data is also easier with CapFrameX compared to just PresentMon.

Besides, the "full project" is around 12MB^^

**Comment by DevTechProfile** [comment]
Maybe addisokw has an archive with many records made with PresentMon. He could analyse this records with CapFrameX. So, we will obviously support that.
