### ISSUE TITLE
Redesign comparison page

### ISSUE THREAD

**Issue by DevTechProfile** [DevTechProfile/CapFrameX#13]
Complete redesign comparison page:
* bar charts (grouping)
* relative mode (Drag&Drop)
* sorting (auto + Drag&Drop)
* better frametime charts

**Comment by Taxxor90** [comment]
- add second context to choose (let us see CPU and GPU, or CPU and RAM, or Comment and RAM ...)
- remove Date/Time from comparison list to make space for the two potential contexts(Date/Time could be set as context anyway)

-Move all Toolbar Options(Comparison/Bar, Comparison/Graph and Analysis) to one place to unify the UI(pictures attached)

![Comparison bar charts](https://user-images.githubusercontent.com/45570250/68489478-765d9700-0247-11ea-8107-612a6f90440d.png)
![Comparison Graphs](https://user-images.githubusercontent.com/45570250/68489481-778ec400-0247-11ea-8bb1-51c041db4088.png)
![Analysis](https://user-images.githubusercontent.com/45570250/68489985-7d38d980-0248-11ea-8243-a81120da46c4.png)

**Comment by Taxxor90** [comment]
- grouping of each game in the record list just like the bar charts with sorting only applied to entries within each list.

![list](https://user-images.githubusercontent.com/45570250/68550149-9f755780-0400-11ea-81c1-701123e55420.png)
