### ISSUE TITLE
Resources Folder name misspelled during creation

### ISSUE THREAD

**Issue by Nvictuz** [DevTechProfile/CapFrameX#20]
During installation two folders are created:

- Captures
- Ressources
![CapFrameXIssue](https://user-images.githubusercontent.com/15676434/68004195-c88e2f00-fc2d-11e9-8644-940de297efe5.PNG)

Ressources is spelled Resources (only two **S** in the word)

**Comment by DevTechProfile** [comment]
Thanks for the report.
