### ISSUE TITLE
Screenshot folder not created during installation

### ISSUE THREAD

**Issue by Nvictuz** [DevTechProfile/CapFrameX#21]
Installation: Default options EXCEPT I chose the e: drive instead of C: drive for app files (folder paths are the same other than drive letter).

In CapFrameX under options:
it shows the relative path for CAPTURES as "MyDocuments\CapFrameX\Captures"
it shows the relative path for SCREENSHOTS as "MyDocuments\CapFrameX\Screenshots"

The screenshots folder is not created during installation like the CAPTURES folder
Additionally a folder called RESSOURCES is created in the same CapFrameX directory.
RESOURCES is the correct spelling.

![CapFrameXIssue](https://user-images.githubusercontent.com/15676434/68005552-dabe9c00-fc32-11e9-8058-0b2ab7b60495.PNG)

**Comment by DevTechProfile** [comment]
Thanks for the report. Strictly speaking, this is not a bug. The folder is created as required during runtime. But I can "tell" the installer to create the folder.
