### ISSUE TITLE
System RAM info: Memory Quantity Inaccurate

### ISSUE THREAD

**Issue by CrispySteak** [DevTechProfile/CapFrameX#3]
I have 2x16 GB of @3200 MT/s which is misreported as 16 GB in the Single Record->System Info (see below vs what cpu-z reports)

OS: Windows 10 Pro x64 Version 1809
![image](https://user-images.githubusercontent.com/8027801/59165749-b250cc80-8aee-11e9-87f6-c945c8060a6a.png)

**Comment by DevTechProfile** [comment]
Ok, thanks for the report. We will fix it.
