### ISSUE TITLE
Request: Cutting Mode enhancement

### ISSUE THREAD

**Issue by Taxxor90** [DevTechProfile/CapFrameX#30]
Is it possible to have the cutting mode not be limited to either 0-49.99% or 50.01% to 100%, for example when I want to see the graph between 85% and 90%?
That way the cutting mode would be sort of a sliding window at the same time.

![cutting mode](https://user-images.githubusercontent.com/45570250/68536668-b1022500-0356-11ea-87eb-e21e274e7b0b.png)

**Comment by DevTechProfile** [comment]
RangeSlider: https://stackoverflow.com/questions/15814623/is-there-a-wpf-control-to-select-a-range-looking-like-a-slider
