### ISSUE TITLE
Structured record folder management

### ISSUE THREAD

**Issue by Taxxor90** [DevTechProfile/CapFrameX#32]
- Option to create and name sub-folders for records within the capture folder through the record list entries(right click)
- context option "create new folder" and "move to folder(show list of sub-folders on click)"
- Drop-Down menu at top of record list to chose sub-folders to show(include "all" option to see all records including the ones in sub folders)
- captures are saved in the currently selected folder
- standard selection on startup is "All", then records go in the main folder

**Comment by DevTechProfile** [comment]
Record data folder area concept
![Area_concept](https://user-images.githubusercontent.com/30285858/75606938-6b7a8b00-5af2-11ea-8c71-21c8992fc63c.png)
