### ISSUE TITLE
Global settings for custom hardware info(and global settings redesign)

### ISSUE THREAD

**Issue by Taxxor90** [DevTechProfile/CapFrameX#33]
- Add toggle to switch between automatically detected HW and custom HW so users who use specific overclocks or timings for their HW in general can add them without having to edit every single record.
- Entries for CPU, GPU and RAM appear if toggled and are used as Info on new captures.

- Make some space in the settings by shrinking various options and group directory settings together.

![Anmerkung 2019-11-15 185344](https://user-images.githubusercontent.com/45570250/68964970-f69d7280-07da-11ea-8633-6c67642c56ed.png)

**Comment by DevTechProfile** [comment]
Quick button to open used folders directly.
