### ISSUE TITLE
Global screenshot button

### ISSUE THREAD

**Issue by Taxxor90** [DevTechProfile/CapFrameX#45]
- Remove screenshot mode switcher from Analysis page and add a global screenshot button next to the global options.

- Screenshot button always captures the complete second colum on the currently active view(e.g. to get the game name on analysis page into the screenshot)

- Leave out toolbar(which should be easy since the toolbar is now at the bottom of every view)

**Comment by Taxxor90** [comment]
- add a "CapFrameX" watermark at a suitable spot to the screenshot

**Comment by DevTechProfile** [comment]
Must solve DPI issue first. 
![ACOrigins exe_2019-27-11_19-39-39_CX_Analysis](https://user-images.githubusercontent.com/30285858/69751572-afef3700-114f-11ea-8e93-19ef34bd8ee4.png)

**Comment by DevTechProfile** [comment]
Test 100% scale
![test100%](https://user-images.githubusercontent.com/30285858/69754432-2bec7d80-1156-11ea-9972-805ae2fcefa1.png)


Test 150% scale
![test150%](https://user-images.githubusercontent.com/30285858/69754436-2e4ed780-1156-11ea-9cf4-34470904df5b.png)

**Comment by Taxxor90** [comment]
Ratio issue is caused by changing the ratio of the window while screenshot mode is active.

Activating Screenshot mode, make a screenshot -> works
Change ratio, make a screenshot -> doesn't work
Deactivating screenshot mode, activating screenshot mode, make a screenshot -> works


Method for new global screenshot button, just one press that causes these actions:
1. activating screenshot mode (Toolbars fade out)
2. making a screenshot
3. prompt a message that a screenshot was made, closed by "OK"
4. deactivating screenshot mode.
