### ISSUE TITLE
Tab "Capture" is missing

### ISSUE THREAD

**Issue by tantrus332** [DevTechProfile/CapFrameX#6]
Windows 7 Home Premium (64-bit, run as administrator)
![изображение](https://user-images.githubusercontent.com/19389131/63229150-89476900-c20e-11e9-96bc-e70cc2709605.png)

**Comment by DevTechProfile** [comment]
The capture page is not missing under Win 7. I've deactivated the capture service (as a consequence the page too)  because it produces system crashes. Sorry. :(

**Comment by DevTechProfile** [comment]
There's a new PresentMon version with better Win 7 support. I'm gonna try to activate the capture page with Win 7.

**Comment by DevTechProfile** [comment]
I'v tested the current PresentMon version (1.5) on Windows 7. It looks good. So capturing will be supported on Win 7. I hope there are no other issues with that old OS...

**Comment by tantrus332** [comment]
Glad to hear that

**Comment by namemane** [comment]
Hello!
Tell me, please, when will you finalize the program for supporting win7?
Or will it be enough for me to change the PresentMon file manually?

**Comment by DevTechProfile** [comment]
I'm still working on it. If you wonna give it a try, check out the branch "develop/feature/redesign_comparison_page".
