### ISSUE TITLE
Create Overlay page

### ISSUE THREAD

**Issue by DevTechProfile** [DevTechProfile/CapFrameX#65]
Create an overlay page which provides overlay and history aggregation configuration capabilities.
![TL0jzqO](https://user-images.githubusercontent.com/30285858/71349695-e6ae4680-256f-11ea-8c2b-a9d20c03e5c1.png)

**Comment by Taxxor90** [comment]
Updated Overlay page to account for the possibility to show a run history without aggregating results
![overlay view](https://user-images.githubusercontent.com/45570250/71469499-a944f580-27c9-11ea-89a3-2cf98e9a386a.png)
