### ISSUE TITLE
Cloud Integration/Sharing Service

### ISSUE THREAD

**Issue by awinnen** [DevTechProfile/CapFrameX#89]
- New option "share" in capture list (right click)
    - Uploades file to sharing service
    - Returns id of the capture and url of the uploaded file
    - Opening Url in Browser will display information about capture file
        - Ability to download capture file from website via browser
- New View to download a shared capture by id or url in CX App
    - Capture file will be downloaded and copied to capture directory

**Comment by Taxxor90** [comment]
* Separate "Cloud" View to add records for sharing and showing IDs and URLs of already uploaded data sets. 
* Options to pull the latest game name and ignore list (to installation folder)
* Options to automatically upload own additions to game name and ignore list
