### ISSUE TITLE
New input lag approximation equation

### ISSUE THREAD

**Issue by DevTechProfile** [DevTechProfile/CapFrameX#95]
Better approach that works no matter which limiter (NV CP, RTSS, ingame) is used: https://github.com/GameTechDev/PresentMon/issues/73#issuecomment-589874806

**Comment by RodroG-85** [comment]
Ok. Now, with that new click-input upper bound approach what would be the best practical method when benchmarking the approximate input lag we get with the different FPS limiters (driver-based, RTSS, and in-game)? What do you think?

**Comment by DevTechProfile** [comment]
We will pursue this question once we have implemented the equation and gained a first impression. I will come back to your soon.

**Comment by RodroG-85** [comment]
> We will pursue this question once we have implemented the equation and gained a first impression. I will come back to your soon.

Got it.

In the mean time, can I use the original approximate input lag equation for benchmarking Nvidia's FPS limiter V1 vs V2 vs V3?

**Comment by DevTechProfile** [comment]
The NV CP Limiter is the only one that can be benched with the old approach.

**Comment by RodroG-85** [comment]
> The NV CP Limiter is the only one that can be benched with the old approach.

Why would only be benched the NV v3 limiter (aka NV CP limiter)? The original equation is supposed to be correct in case of driver/OS based limiters though, and V1, V2 and V3 (NV CP) are all driver-based limiters.

Is there anything I'm missing here? Thanks in advance.

**Comment by DevTechProfile** [comment]
Yes, what I mean are all driver based limiters.

**Comment by xcasxcursex** [comment]
Hi, long time lurker first time poster, here  ;) If I may make a suggestion....

As per https://github.com/GameTechDev/PresentMon/issues/73#issuecomment-590985289 I would suggest you plot the latency as a line with shaded error area, that way you get all three (lower, upper, and expected latency) in one plot.

Anyway since I'm posting... I've been doing all this manually for a long time, and it's bloody fantastic to see someone making a tool for it so I don't have to do it the hard way any more. Thanks guys.

**Comment by DevTechProfile** [comment]
@xcasxcursex I think it's a good proposal. We will provide lower, upper, and expected latency graphs in one plot and average lower, upper, and expected latency in the bar chart.

**Comment by Taxxor90** [comment]
The current state of input lag page

![Screenshot_2020-27-2_17-07-41_CX_Analysis](https://user-images.githubusercontent.com/45570250/75464016-e1fa7a00-5986-11ea-9e03-259ed3453d94.png)

**Comment by RodroG-85** [comment]
Amazing job. Thank you!
